Repository Figci/Figci-Server, pull requests merged in 2024-02, with the labels that each got.

#5 Chore: 패키지 설치 및 보일러 플레이트 작성
  .eslintrc.js
  .gitignore
  .husky/pre-commit
  .prettierrc.json
  app.js
  bin/www
  package-lock.json
  package.json
  src/constants/config.js
  src/constants/error.js
  src/loaders/index.js
Labels: enhancement, D-0

#9 Chore: 라우터 설정 및 appLoader 연결
  bin/www
  src/constants/config.js
  src/loaders/express.js
  src/loaders/index.js
  src/loaders/mongoose.js
  src/loaders/routers.js
  src/routers/projects.js
Labels: D-0

#10 Feature: Document/Result Schema 모델 작성
  src/models/Document.js
  src/models/Result.js
Labels: D-0

#11 Feature: 프로젝트 버전 요청 API 응답 및 에러 처리
  package-lock.json
  package.json
  src/constants/config.js
  src/loaders/express.js
  src/routers/projects.js
Labels: D-0

#12 Feature: 버전 공통 페이지 응답 및 서브트리 DB저장 기능 구현
  .eslintrc.js
  src/constants/constants.js
  src/constants/error.js
  src/controllers/projectController.js
  src/loaders/error.js
  src/loaders/index.js
  src/models/Document.js
  src/routers/projects.js
  src/utils/comparePages.js
  src/utils/saveFigmaDataAsNestedStructure.js
Labels: D-0

#14 ♻️ Refactor: response구조 변경
  src/controllers/projectController.js
Labels: TBR

#23 Feature: userRouter 구현
  src/controllers/userController.js
  src/loaders/routers.js
  src/routers/user.js
Labels: ASAP

#24 Fix: userRouter response구조 수정
  src/controllers/userController.js
Labels: bug

#25 HotFix: diffing시 widget타입을 만나면 에러 발생 수정
  src/utils/getDiffing.js
Labels: bug
